files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%osx_locale%/strings.xml
    languages_mapping:
      osx_locale:
        en-GB: en-rGB
        en-US: en-rUS
        pt-BR: pt-rBR
        es-US: es-rUS
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        he: iw
  - source: /fastlane/metadata/android/en-US/*.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
